// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { GroupsListUserGroupsData, GroupsListUserGroupsResponse, GroupsCreateGroupData, GroupsCreateGroupResponse, GroupsReadGroupData, GroupsReadGroupResponse, GroupsUpdateGroupData, GroupsUpdateGroupResponse, GroupsDeleteGroupData, GroupsDeleteGroupResponse, GroupsAddGroupMemberData, GroupsAddGroupMemberResponse, GroupsRemoveGroupMemberData, GroupsRemoveGroupMemberResponse, GroupsListCurrentUserGroupExpensesData, GroupsListCurrentUserGroupExpensesResponse, GroupsListGroupExpensesData, GroupsListGroupExpensesResponse, GroupsCreateExpenseData, GroupsCreateExpenseResponse, GroupsUpdateExpenseData, GroupsUpdateExpenseResponse, GroupsDeleteExpenseData, GroupsDeleteExpenseResponse, GroupsCreateSettlementPaymentData, GroupsCreateSettlementPaymentResponse, ItemsReadItemsData, ItemsReadItemsResponse, ItemsCreateItemData, ItemsCreateItemResponse, ItemsReadItemData, ItemsReadItemResponse, ItemsUpdateItemData, ItemsUpdateItemResponse, ItemsDeleteItemData, ItemsDeleteItemResponse, LoginLoginAccessTokenData, LoginLoginAccessTokenResponse, LoginTestTokenResponse, LoginRecoverPasswordData, LoginRecoverPasswordResponse, LoginResetPasswordData, LoginResetPasswordResponse, LoginRecoverPasswordHtmlContentData, LoginRecoverPasswordHtmlContentResponse, PrivateCreateUserData, PrivateCreateUserResponse, UsersReadUsersData, UsersReadUsersResponse, UsersCreateUserData, UsersCreateUserResponse, UsersReadUserMeResponse, UsersDeleteUserMeResponse, UsersUpdateUserMeData, UsersUpdateUserMeResponse, UsersUpdatePasswordMeData, UsersUpdatePasswordMeResponse, UsersReadUserProfileResponse, UsersRegisterUserData, UsersRegisterUserResponse, UsersReadUserByIdData, UsersReadUserByIdResponse, UsersUpdateUserData, UsersUpdateUserResponse, UsersDeleteUserData, UsersDeleteUserResponse, UtilsTestEmailData, UtilsTestEmailResponse, UtilsHealthCheckResponse } from './types.gen';

export class GroupsService {
    /**
     * List User Groups
     * Listar los grupos del usuario autenticado.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns GroupsPublic Successful Response
     * @throws ApiError
     */
    public static listUserGroups(data: GroupsListUserGroupsData = {}): CancelablePromise<GroupsListUserGroupsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/groups/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Group
     * Crear un nuevo grupo.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns GroupPublic Successful Response
     * @throws ApiError
     */
    public static createGroup(data: GroupsCreateGroupData): CancelablePromise<GroupsCreateGroupResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/groups/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Group
     * Obtener detalle de un grupo y sus integrantes.
     * @param data The data for the request.
     * @param data.groupId
     * @returns GroupDetailPublic Successful Response
     * @throws ApiError
     */
    public static readGroup(data: GroupsReadGroupData): CancelablePromise<GroupsReadGroupResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/groups/{group_id}',
            path: {
                group_id: data.groupId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Group
     * Editar configuracion basica de un grupo.
     * @param data The data for the request.
     * @param data.groupId
     * @param data.requestBody
     * @returns GroupDetailPublic Successful Response
     * @throws ApiError
     */
    public static updateGroup(data: GroupsUpdateGroupData): CancelablePromise<GroupsUpdateGroupResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/groups/{group_id}',
            path: {
                group_id: data.groupId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Group
     * Eliminar un grupo.
     * @param data The data for the request.
     * @param data.groupId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteGroup(data: GroupsDeleteGroupData): CancelablePromise<GroupsDeleteGroupResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/groups/{group_id}',
            path: {
                group_id: data.groupId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Add Group Member
     * Anadir participante a un grupo por email.
     * @param data The data for the request.
     * @param data.groupId
     * @param data.requestBody
     * @returns GroupMemberPublic Successful Response
     * @throws ApiError
     */
    public static addGroupMember(data: GroupsAddGroupMemberData): CancelablePromise<GroupsAddGroupMemberResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/groups/{group_id}/members',
            path: {
                group_id: data.groupId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Remove Group Member
     * Quitar participante de un grupo.
     * @param data The data for the request.
     * @param data.groupId
     * @param data.userId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static removeGroupMember(data: GroupsRemoveGroupMemberData): CancelablePromise<GroupsRemoveGroupMemberResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/groups/{group_id}/members/{user_id}',
            path: {
                group_id: data.groupId,
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * List Current User Group Expenses
     * Listar todos los gastos de los grupos del usuario con el monto que le corresponde.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns UserExpensesPublic Successful Response
     * @throws ApiError
     */
    public static listCurrentUserGroupExpenses(data: GroupsListCurrentUserGroupExpensesData = {}): CancelablePromise<GroupsListCurrentUserGroupExpensesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/groups/me/expenses',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * List Group Expenses
     * Listar los gastos de un grupo para sus miembros.
     * @param data The data for the request.
     * @param data.groupId
     * @param data.skip
     * @param data.limit
     * @returns ExpensesPublic Successful Response
     * @throws ApiError
     */
    public static listGroupExpenses(data: GroupsListGroupExpensesData): CancelablePromise<GroupsListGroupExpensesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/groups/{group_id}/expenses',
            path: {
                group_id: data.groupId
            },
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Expense
     * Registrar un nuevo gasto en un grupo.
     * @param data The data for the request.
     * @param data.groupId
     * @param data.requestBody
     * @returns ExpensePublic Successful Response
     * @throws ApiError
     */
    public static createExpense(data: GroupsCreateExpenseData): CancelablePromise<GroupsCreateExpenseResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/groups/{group_id}/expenses',
            path: {
                group_id: data.groupId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Expense
     * Modificar un gasto de un grupo.
     * @param data The data for the request.
     * @param data.groupId
     * @param data.expenseId
     * @param data.requestBody
     * @returns ExpensePublic Successful Response
     * @throws ApiError
     */
    public static updateExpense(data: GroupsUpdateExpenseData): CancelablePromise<GroupsUpdateExpenseResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/groups/{group_id}/expenses/{expense_id}',
            path: {
                group_id: data.groupId,
                expense_id: data.expenseId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Expense
     * Eliminar un gasto de un grupo y revertir su impacto en saldos.
     * @param data The data for the request.
     * @param data.groupId
     * @param data.expenseId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteExpense(data: GroupsDeleteExpenseData): CancelablePromise<GroupsDeleteExpenseResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/groups/{group_id}/expenses/{expense_id}',
            path: {
                group_id: data.groupId,
                expense_id: data.expenseId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Settlement Payment
     * Registrar un pago de deuda sobre la liquidacion sugerida actual.
     * @param data The data for the request.
     * @param data.groupId
     * @param data.requestBody
     * @returns SettlementPaymentPublic Successful Response
     * @throws ApiError
     */
    public static createSettlementPayment(data: GroupsCreateSettlementPaymentData): CancelablePromise<GroupsCreateSettlementPaymentResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/groups/{group_id}/settlement-payments',
            path: {
                group_id: data.groupId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class ItemsService {
    /**
     * Read Items
     * Retrieve items.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns ItemsPublic Successful Response
     * @throws ApiError
     */
    public static readItems(data: ItemsReadItemsData = {}): CancelablePromise<ItemsReadItemsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/items/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Item
     * Create new item.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static createItem(data: ItemsCreateItemData): CancelablePromise<ItemsCreateItemResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/items/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Item
     * Get item by ID.
     * @param data The data for the request.
     * @param data.id
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static readItem(data: ItemsReadItemData): CancelablePromise<ItemsReadItemResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Item
     * Update an item.
     * @param data The data for the request.
     * @param data.id
     * @param data.requestBody
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static updateItem(data: ItemsUpdateItemData): CancelablePromise<ItemsUpdateItemResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Item
     * Delete an item.
     * @param data The data for the request.
     * @param data.id
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteItem(data: ItemsDeleteItemData): CancelablePromise<ItemsDeleteItemResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class LoginService {
    /**
     * Login Access Token
     * OAuth2 compatible token login, get an access token for future requests
     * @param data The data for the request.
     * @param data.formData
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static loginAccessToken(data: LoginLoginAccessTokenData): CancelablePromise<LoginLoginAccessTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/access-token',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Test Token
     * Test access token
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static testToken(): CancelablePromise<LoginTestTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/test-token'
        });
    }
    
    /**
     * Recover Password
     * Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static recoverPassword(data: LoginRecoverPasswordData): CancelablePromise<LoginRecoverPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Reset Password
     * Reset password
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static resetPassword(data: LoginResetPasswordData): CancelablePromise<LoginResetPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/reset-password/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Recover Password Html Content
     * HTML Content for Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns string Successful Response
     * @throws ApiError
     */
    public static recoverPasswordHtmlContent(data: LoginRecoverPasswordHtmlContentData): CancelablePromise<LoginRecoverPasswordHtmlContentResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery-html-content/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class PrivateService {
    /**
     * Create User
     * Create a new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: PrivateCreateUserData): CancelablePromise<PrivateCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/private/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UsersService {
    /**
     * Read Users
     * Retrieve users.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns UsersPublic Successful Response
     * @throws ApiError
     */
    public static readUsers(data: UsersReadUsersData = {}): CancelablePromise<UsersReadUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create User
     * Create new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: UsersCreateUserData): CancelablePromise<UsersCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User Me
     * Get current user.
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Delete User Me
     * Delete own user.
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Update User Me
     * Update own user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUserMe(data: UsersUpdateUserMeData): CancelablePromise<UsersUpdateUserMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Password Me
     * Update own password.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static updatePasswordMe(data: UsersUpdatePasswordMeData): CancelablePromise<UsersUpdatePasswordMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me/password',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User Profile
     * Obtener perfil del usuario autenticado con datos garantizados para la UI.
     * @returns UserProfileInfo Successful Response
     * @throws ApiError
     */
    public static readUserProfile(): CancelablePromise<UsersReadUserProfileResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me/profile'
        });
    }
    
    /**
     * Register User
     * Create new user without the need to be logged in.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static registerUser(data: UsersRegisterUserData): CancelablePromise<UsersRegisterUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/signup',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User By Id
     * Get a specific user by id.
     * @param data The data for the request.
     * @param data.userId
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserById(data: UsersReadUserByIdData): CancelablePromise<UsersReadUserByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update User
     * Update a user.
     * @param data The data for the request.
     * @param data.userId
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUser(data: UsersUpdateUserData): CancelablePromise<UsersUpdateUserResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete User
     * Delete a user.
     * @param data The data for the request.
     * @param data.userId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUser(data: UsersDeleteUserData): CancelablePromise<UsersDeleteUserResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UtilsService {
    /**
     * Test Email
     * Test emails.
     * @param data The data for the request.
     * @param data.emailTo
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static testEmail(data: UtilsTestEmailData): CancelablePromise<UtilsTestEmailResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/utils/test-email/',
            query: {
                email_to: data.emailTo
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Health Check
     * @returns boolean Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/health-check/'
        });
    }
}