// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type ExpenseCreate = {
    description: string;
    amount: number;
    payer_id: string;
    participants?: Array<ExpenseParticipantIn>;
    division_mode: 'equitable' | 'custom';
};

export type division_mode = 'equitable' | 'custom';

export type ExpenseParticipantIn = {
    user_id: string;
    amount?: (number | null);
};

export type ExpenseParticipantPublic = {
    user_id: string;
    amount_owed: number;
};

export type ExpensePublic = {
    description: string;
    amount: number;
    id: string;
    group_id: string;
    payer_id: string;
    created_at: string;
    participants: Array<ExpenseParticipantPublic>;
};

export type ExpensesPublic = {
    data: Array<ExpensePublic>;
    count: number;
};

export type GroupCreate = {
    name: string;
    description?: (string | null);
};

export type GroupDetailPublic = {
    name: string;
    description?: (string | null);
    id: string;
    created_at: string;
    current_user_balance: number;
    members: Array<GroupMemberPublic>;
    settlement_payments: Array<SettlementPaymentPublic>;
};

export type GroupMemberCreate = {
    email: string;
    is_admin?: boolean;
};

export type GroupMemberPublic = {
    user_id: string;
    email: string;
    full_name?: (string | null);
    is_admin: boolean;
    balance: number;
    joined_at: string;
};

export type GroupPublic = {
    name: string;
    description?: (string | null);
    id: string;
    created_at: string;
    current_user_balance: number;
};

export type GroupsPublic = {
    data: Array<GroupPublic>;
    count: number;
};

export type GroupUpdate = {
    name?: (string | null);
    description?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type SettlementPaymentCreate = {
    amount: (number | string);
    from_user_id: string;
    to_user_id: string;
    payment_date?: (string | null);
};

export type SettlementPaymentPublic = {
    amount: number;
    id: string;
    group_id: string;
    from_user_id: string;
    to_user_id: string;
    created_at: string;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserExpensePublic = {
    expense_id: string;
    group_id: string;
    group_name: string;
    description: string;
    amount: number;
    payer_id: string;
    created_at: string;
    current_user_amount_owed: number;
};

export type UserExpensesPublic = {
    data: Array<UserExpensePublic>;
    count: number;
};

export type UserProfileInfo = {
    id: string;
    email: string;
    full_name?: (string | null);
    display_name: string;
    initial: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type GroupsListUserGroupsData = {
    limit?: number;
    skip?: number;
};

export type GroupsListUserGroupsResponse = (GroupsPublic);

export type GroupsCreateGroupData = {
    requestBody: GroupCreate;
};

export type GroupsCreateGroupResponse = (GroupPublic);

export type GroupsReadGroupData = {
    groupId: string;
};

export type GroupsReadGroupResponse = (GroupDetailPublic);

export type GroupsUpdateGroupData = {
    groupId: string;
    requestBody: GroupUpdate;
};

export type GroupsUpdateGroupResponse = (GroupDetailPublic);

export type GroupsDeleteGroupData = {
    groupId: string;
};

export type GroupsDeleteGroupResponse = (Message);

export type GroupsAddGroupMemberData = {
    groupId: string;
    requestBody: GroupMemberCreate;
};

export type GroupsAddGroupMemberResponse = (GroupMemberPublic);

export type GroupsRemoveGroupMemberData = {
    groupId: string;
    userId: string;
};

export type GroupsRemoveGroupMemberResponse = (Message);

export type GroupsListCurrentUserGroupExpensesData = {
    limit?: number;
    skip?: number;
};

export type GroupsListCurrentUserGroupExpensesResponse = (UserExpensesPublic);

export type GroupsListGroupExpensesData = {
    groupId: string;
    limit?: number;
    skip?: number;
};

export type GroupsListGroupExpensesResponse = (ExpensesPublic);

export type GroupsCreateExpenseData = {
    groupId: string;
    requestBody: ExpenseCreate;
};

export type GroupsCreateExpenseResponse = (ExpensePublic);

export type GroupsCreateSettlementPaymentData = {
    groupId: string;
    requestBody: SettlementPaymentCreate;
};

export type GroupsCreateSettlementPaymentResponse = (SettlementPaymentPublic);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersReadUserProfileResponse = (UserProfileInfo);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);